on: [push]

name: build

jobs:
  build_java_11_jdk_slim_aws:
    name: Build 11 jdk slim aws
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build and Publish Docker Images
      run: |
        ./ci/bin/docker_build_and_push.sh 11/jdk/slim-aws openjdk:11-aws openjdk:11-jdk-aws openjdk:11-jdk-slim-aws openjdk:11.0.6-jdk-slim-aws
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
        GITHUB_ORGANIZATION: ${{ secrets.GITHUB_ORGANIZATION }}

  build_java_11_jdk_slim:
    name: Build 11 jdk slim
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build and Publish Docker Images
      run: |
        ./ci/bin/docker_build_and_push.sh 11/jdk/slim openjdk openjdk:11 openjdk:11-jdk openjdk:11-jdk-slim openjdk:11.0.6-jdk-slim
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
        GITHUB_ORGANIZATION: ${{ secrets.GITHUB_ORGANIZATION }}

  build_java_11_jdk_zulu:
    name: Build 11 jdk zulu
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build and Publish Docker Images
      run: |
        ./ci/bin/docker_build_and_push.sh 11/jdk/zulu openjdk:11-zulu openjdk:11-jdk-zulu openjdk:11-jdk-zulu openjdk:11.0.5-jdk-zulu
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
        GITHUB_ORGANIZATION: ${{ secrets.GITHUB_ORGANIZATION }}

  build_java_11_jdk_zulu_docker:
    name: Build 11 jdk zulu docker
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build and Publish Docker Images
      run: |
        ./ci/bin/docker_build_and_push.sh 11/jdk/zulu-docker openjdk:11-zulu-docker openjdk:11-jdk-zulu-docker openjdk:11-jdk-zulu-docker openjdk:11.0.5-jdk-zulu-docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
        GITHUB_ORGANIZATION: ${{ secrets.GITHUB_ORGANIZATION }}

  build_java_11_jre_slim_aws:
    name: Build 11 jre slim aws 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build and Publish Docker Images
      run: |
        ./ci/bin/docker_build_and_push.sh 11/jre/slim-aws openjdk:11-jre-aws openjdk:11-jre-slim-aws openjdk:11.0.6-jre-slim-aws
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
        GITHUB_ORGANIZATION: ${{ secrets.GITHUB_ORGANIZATION }}

  build_java_11_jre_slim:
    name: Build 11 jre slim 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build and Publish Docker Images
      run: |
        ./ci/bin/docker_build_and_push.sh 11/jre/slim openjdk:11-jre openjdk:11-jre-slim openjdk:11.0.6-jre-slim
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
        GITHUB_ORGANIZATION: ${{ secrets.GITHUB_ORGANIZATION }}

  build_java_8_jdk_alpine:
    name: Build 8 JDK alpine 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build and Publish Docker Images
      run: |
        ./ci/bin/docker_build_and_push.sh 8/jdk/alpine openjdk:8 openjdk:8-jdk openjdk:8-jdk-alpine openjdk:8u201-jdk-alpine openjdk:8u201-jdk-alpine3.9
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
        GITHUB_ORGANIZATION: ${{ secrets.GITHUB_ORGANIZATION }}

  build_java_8_jre_alpine:
    name: Build 8 JRE alpine 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build and Publish Docker Images
      run: |
        ./ci/bin/docker_build_and_push.sh 8/jre/alpine openjdk:8-jre openjdk:8-jre-alpine openjdk:8u201-jre-alpine openjdk:8u201-jre-alpine3.9
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
        GITHUB_ORGANIZATION: ${{ secrets.GITHUB_ORGANIZATION }}

